---
version: 0.2

env:
  variables:
    KEY: "value"

phases:
  install:
    commands:
      - aws --version
  pre_build:
    commands:
      - echo "Some variables"
      - echo ${WEBSITE_BUCKET_NAME}
      - echo ${CODEBUILD_SOURCE_VERSION}
  build:
    commands:
      - make doc rss
  post_build:
    commands:
      - echo Post build command. Doint nothing.
      - aws s3 cp --recursive  --acl public-read  build/   s3://${WEBSITE_BUCKET_NAME}/


